// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhuNbtMEmR4FKsZDUdicW3oDrZdHWMIQM',
    appId: '1:671341198392:web:698d97802ab75daffebacd',
    messagingSenderId: '671341198392',
    projectId: 'help-desk-lite-e73f2',
    authDomain: 'help-desk-lite-e73f2.firebaseapp.com',
    storageBucket: 'help-desk-lite-e73f2.firebasestorage.app',
    measurementId: 'G-FNLTGM2QK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu4Q39fDxgZPd_YmDr-toTNyBpN_jW4Ec',
    appId: '1:671341198392:android:3daae98a465e790dfebacd',
    messagingSenderId: '671341198392',
    projectId: 'help-desk-lite-e73f2',
    storageBucket: 'help-desk-lite-e73f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALUEbmw-mQzNk8Z2sn2QduXuO3BenNKoI',
    appId: '1:671341198392:ios:d3a900b3aa1ce5b9febacd',
    messagingSenderId: '671341198392',
    projectId: 'help-desk-lite-e73f2',
    storageBucket: 'help-desk-lite-e73f2.firebasestorage.app',
    iosBundleId: 'com.example.helpDeskLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhuNbtMEmR4FKsZDUdicW3oDrZdHWMIQM',
    appId: '1:671341198392:web:ecb1453e68266ad3febacd',
    messagingSenderId: '671341198392',
    projectId: 'help-desk-lite-e73f2',
    authDomain: 'help-desk-lite-e73f2.firebaseapp.com',
    storageBucket: 'help-desk-lite-e73f2.firebasestorage.app',
    measurementId: 'G-WS9M5HKH7N',
  );
}
